### ISSUE TITLE
npm ERR! request to https://registry.cnpmjs.org/appium-doctor failed, reason: Hostname/IP does not match certificate's altnames: Host: registry.cnpmjs.org. is not in the cert's altnames: DNS:r.cnpmjs.org

### ISSUE THREAD

**Issue by macro-c** [appium/appium-doctor#123] opened 2021-08-10 07:03 UTC
error just like title says.

**Comment by KazuCocoa** [comment] 2021-08-11 00:26
Duplicate of https://github.com/appium/appium/issues/15707

**Closed by KazuCocoa** 2021-08-11 00:26 UTC
